### ISSUE TITLE
Cannot run on Node 10

### ISSUE THREAD

**Issue by fuyifan** [szmarczak/cacheable-lookup#30]
const {
	V4MAPPED,
	ADDRCONFIG,
	promises: {
		Resolver: AsyncResolver
	},
	lookup
} = require('dns');

TypeError: Cannot destructure property `Resolver` of 'undefined' or 'null'.
    at Object.<anonymous> (d:\parapara_oppo\server\LoginServer\node_modules\cacheable-lookup\source\index.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by szmarczak** [comment]
Update your Node.js 10 version.

**Comment by szmarczak** [comment]
https://nodejs.org/docs/latest-v10.x/api/dns.html#dns_dns_promises_api
