### ISSUE TITLE
No way to dispose and timeout problems

### ISSUE THREAD

**Issue by phawxby** [szmarczak/cacheable-lookup#74]
I've been trying to figure out problems with tests not disposing very well and I appear to have narrowed it down to CacheableLookup, and specifically the timeout within `_tick`, there's no way to dispose it externally. 

Forgive the long stack.
```
    console.warn
      Uncleared call to setTimeout at "node_modules/timeout-monitor/src/timeout-monitor.js", line 91, column 24
      
      Error: 
          at findCallerLocation (/Users/paul/Documents/GitHub/brand-engine/node_modules/timeout-monitor/src/find-caller-location.js:30:16)
          at monitor._global.setTimeout (/Users/paul/Documents/GitHub/brand-engine/node_modules/timeout-monitor/src/timeout-monitor.js:91:24)
          at CacheableLookup._tick (/Users/paul/Documents/GitHub/brand-engine/node_modules/cacheable-lookup/source/index.js:352:27)
          at CacheableLookup._set (/Users/paul/Documents/GitHub/brand-engine/node_modules/cacheable-lookup/source/index.js:317:10)
          at CacheableLookup.queryAndCache (/Users/paul/Documents/GitHub/brand-engine/node_modules/cacheable-lookup/source/index.js:339:3)
          at CacheableLookup.query (/Users/paul/Documents/GitHub/brand-engine/node_modules/cacheable-lookup/source/index.js:210:15)
          at CacheableLookup.lookupAsync (/Users/paul/Documents/GitHub/brand-engine/node_modules/cacheable-lookup/source/index.js:159:16)
```

Unless otherwise specified the cache duration is 3600 seconds, or 1 hour. As a result the next tick where `this._removalTimeout` can be cleared is an hour away which holds the tests open. There needs to be a check after `clear()` to see if there are any entries in the cache, if not clear the timeout. Failing that there needs to be a `dispose` function` implemented to clear cache and kill timeouts. 

I would appreciate if this fix could be back-ported to the non-ESM release.

**Comment by phawxby** [comment]
Actually after more reading I realise that `cacheable-lookup` is using https://nodejs.org/api/timers.html#timeoutunref so it's likely not this. The hunt continues!
