### ISSUE TITLE
error: Expected an Agent instance as the first argument

### ISSUE THREAD

**Issue by diavrank** [szmarczak/cacheable-lookup#84]
Hi, I am migrating my Nestjs app to use Bun js and I am getting this error:

```shell
[8:41:04 PM] Starting compilation in watch mode...

[8:41:30 PM] Found 0 errors. Watching for file changes.

17 | 
18 | const supportsALL = typeof ALL === 'number';
19 | 
20 | const verifyAgent = agent => {
21 |    if (!(agent && typeof agent.createConnection === 'function')) {
22 |            throw new Error('Expected an Agent instance as the first argument');
             ^
error: Expected an Agent instance as the first argument
      at verifyAgent (/Users/diavrank/app/node_modules/cacheable-lookup/source/index.js:22:9)
      at install (/Users/diavrank/app/node_modules/cacheable-lookup/source/index.js:394:3)
      at new Request (/Users/diavrank/app/node_modules/amply.js/lib/request.js:65:19)
      at new Client (/Users/diavrank/app/node_modules/amply.js/lib/client.js:9:20)
      at /Users/diavrank/app/node_modules/amply.js/index.js:4:18
      at /Users/diavrank/app/node_modules/dd-trace/packages/dd-trace/src/ritm.js:97:33
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/dist/commons/services/email.service.js:17:20
      at /Users/diavrank/app/node_modules/dd-trace/packages/dd-trace/src/ritm.js:97:33
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/dist/app/events/events.service.js:105:7
      at /Users/diavrank/app/node_modules/dd-trace/packages/dd-trace/src/ritm.js:97:33
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/dist/commons/services/eraseme.service.js:7:7
      at /Users/diavrank/app/node_modules/dd-trace/packages/dd-trace/src/ritm.js:97:33
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/dist/app/create-event/create-event.service.js:15:7
      at /Users/diavrank/app/node_modules/dd-trace/packages/dd-trace/src/ritm.js:97:33
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/dist/app/companies/connections/services/connections.service.js:53:7
      at /Users/diavrank/app/node_modules/dd-trace/packages/dd-trace/src/ritm.js:97:33
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/dist/app/companies/services/admin-onboarding.service.js:22:7
      at /Users/diavrank/app/node_modules/dd-trace/packages/dd-trace/src/ritm.js:97:33
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39
      at /Users/diavrank/app/node_modules/require-in-the-middle/index.js:188:39

Bun v1.1.34 (macOS arm64)
```

Command to run Nest app:
```shell
bun start
```

start script in package.json
```json
"start": "bun NODE_ENV=localdev nest start --watch --exec \"bun run\"",
```

I am using **amply.js** library that uses this package on its version 6.0.4

**Comment by franchb** [comment]
Got the same error while trying to run **firecrawl** with bun

**Comment by KaoSDlanor** [comment]
Bun doesn't have a global agent that is used by default with all requests for some reason. They do however support the agent class in general so perhaps you can create an agent, install cacheable-lookup on that agent and submit it as an option to your requests?

Something like this:
```TypeScript
import http, { Agent, type RequestOptions } from "node:http";
import CacheableLookup from "cacheable-lookup";

const cacheableLookup = new CacheableLookup();
const cacheableAgent = new Agent();
cacheableLookup.install(cacheableAgent);

export const httpRequestWithDnsCache = function(url: string, options: RequestOptions = {}) {
	if (options.agent instanceof Agent) {
		cacheableLookup.install(options.agent);
	} else {
		options.agent = cacheableAgent;
	}
	return http.request(url, options);
};
```

It's not ideal but maybe it can be a workaround for now

**Comment by KaoSDlanor** [comment]
Unfortunately there is an open issue for using agents in Bun so I am not sure whether this will actually work
https://github.com/oven-sh/bun/issues/2274
